title: "Sebastián Sifontes Valentín"
author: "Sebastián Sifontes Valentín"
email: "tu_email@ejemplo.com"
description: "Economist & Public Manager | Sustainable Policy | Data Science"
baseurl: ""
url: "https://sebastiansifontes.github.io"
github_username: sebastiansifontes
markdown: kramdown
theme: minima